'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {BookOpen,Upload,BarChart3,Plus,ArrowLeft,Check,RotateCcw,Download,RefreshCw,Smartphone,MoreHorizontal} from 'lucide-react';
import {parseCsv,csvCell,jstDate,schedule,type Card,type Rating} from '../lib/study';

type Deck={id:string;name:string;total:number;due:number;learned:number};
type Day={day:string;count:number;good:number;duration:number};
type Data={user:{email:string};decks:Deck[];daily:Day[];summary:{count:number;good:number;duration:number};recent:{id:string;front:string;name:string;rating:Rating;reviewed_at:number;next_due:number}[];serverTime:number};
type Draft={front:string;back:string;note:string;tags:string};
const blank:Draft={front:'',back:'',note:'',tags:''};
async function api<T = Data & { cards: Card[]; count: number }>(path='',body?:unknown){const r=await fetch('/api/study'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await r.json() as T & {error?:string};if(!r.ok){const e=new Error(data.error||'通信に失敗しました。') as Error&{status:number};e.status=r.status;throw e}return data;}
function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function date(n:number){return new Date(n).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();onClose()}} aria-label={title}><div className="section-title"><h2>{title}</h2><button className="text-button" onClick={onClose} aria-label="閉じる">閉じる</button></div>{children}</dialog>}

export default function Workspace(){
 const [tab,setTab]=useState('decks'),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[auth,setAuth]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[offline,setOffline]=useState(false);
 const lock=useRef(false),[selected,setSelected]=useState<Deck|null>(null),[cards,setCards]=useState<Card[]>([]),[search,setSearch]=useState(''),[modal,setModal]=useState<'card'|'rename'|'delete'|null>(null),[draft,setDraft]=useState<Draft>(blank),[editing,setEditing]=useState<Card|null>(null),[name,setName]=useState('');
 const [session,setSession]=useState<Card[]>([]),[position,setPosition]=useState(0),[revealed,setRevealed]=useState(false),[hint,setHint]=useState(false),[right,setRight]=useState(0),[complete,setComplete]=useState(false),[pending,setPending]=useState<{eventId:string;rating:Rating;durationMs:number}|null>(null);const started=useRef(0),touch=useRef<{x:number;y:number}|null>(null);
 const refresh=useCallback(async()=>{const d=await api();setData(d);setAuth(false);return d as Data},[]);
 const run=useCallback(async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'操作できませんでした。');if((e as {status?:number}).status===401)setAuth(true)}finally{lock.current=false;setBusy(false)}},[]);
 useEffect(()=>{refresh().catch(e=>{if(e.status===401)setAuth(true);else setError(e.message)}).finally(()=>setLoading(false));const online=()=>{setOffline(!navigator.onLine);if(navigator.onLine)refresh().catch(()=>{})};online();window.addEventListener('online',online);window.addEventListener('offline',online);const focus=()=>{if(!lock.current)refresh().catch(()=>{})};window.addEventListener('focus',focus);const timer=setInterval(focus,60000);if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{clearInterval(timer);window.removeEventListener('online',online);window.removeEventListener('offline',online);window.removeEventListener('focus',focus)}},[refresh]);
 useEffect(()=>{type Context={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_study_progress',title:'学習状況を読む',description:'ログイン中のユーザーの単語帳、復習予定、日別学習回数と直近の学習履歴を取得する。学習を実行したり評価を変更したりしない。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('引数は空のオブジェクトです。');return await refresh()}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[refresh]);
 const navigate=(next:string)=>{if(lock.current)return;setTab(next);setError('');setNotice('');setSelected(null);setComplete(false);setPending(null)};
 const openDeck=(deck:Deck)=>run(async()=>{const r=await api('?deck='+deck.id);setSelected(deck);setCards(r.cards);setSearch('');setTab('manage')});
 const study=(deck:Deck)=>run(async()=>{const r=await api('?deck='+deck.id);const due=r.cards.filter((c:Card)=>c.due<=(r.serverTime||Date.now())).slice(0,100);if(!due.length){setNotice('いま復習待ちはありません。次の復習時間にまた開いてください。');await refresh();return}setNotice('');setSelected(deck);setSession(due);setPosition(0);setRight(0);setRevealed(false);setHint(false);setPending(null);setComplete(false);started.current=Date.now();setTab('study')});
 const rate=useCallback((rating:Rating)=>{if(!revealed||!session[position]||lock.current||offline||(pending&&pending.rating!==rating))return;const request=pending||{eventId:crypto.randomUUID(),rating,durationMs:Math.max(0,Date.now()-started.current)};setPending(request);void run(async()=>{const card=session[position];await api('',{action:'review',cardId:card.id,version:card.version,...request});setPending(null);setRight(n=>n+(rating==='good'?1:0));setPosition(p=>p+1);setRevealed(false);setHint(false);started.current=Date.now();if(position+1===session.length){setComplete(true);await refresh()}})},[revealed,session,position,offline,pending,run,refresh]);
 useEffect(()=>{if(tab!=='study'||complete)return;const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select,button,a'))return;if(e.code==='Space'){e.preventDefault();setRevealed(true)}if(e.key==='1'||e.key==='ArrowLeft')rate('again');if(e.key==='2'||e.key==='ArrowRight')rate('good')};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[tab,complete,rate]);
 const saveCard=(e:React.FormEvent)=>{e.preventDefault();void run(async()=>{if(!selected)return;if(editing)await api('',{action:'editCard',deckId:selected.id,cardId:editing.id,version:editing.version,...draft});else await api('',{action:'import',deckId:selected.id,operationId:manualOperation.current,cards:[draft]});setModal(null);setCards((await api('?deck='+selected.id)).cards);await refresh();setNotice('カードを保存しました。')})};
 const manualOperation=useRef('');
 const today=jstDate(Date.now()),todayCount=data?.daily.find(x=>x.day===today)?.count||0,total=data?.decks.reduce((n,d)=>n+d.total,0)||0,due=data?.decks.reduce((n,d)=>n+d.due,0)||0;
 let streak=0;for(let i=0;i<366;i++){const day=jstDate(Date.now()-i*86400000);if(data?.daily.some(d=>d.day===day&&d.count>0))streak++;else if(i!==0)break;}
 const card=session[position];const currentDeck=data?.decks.find(d=>d.id===selected?.id)||selected;
 return <div className="shell"><header className="topbar"><div className="brand"><span className="mark">n</span>newanki</div><nav className="nav" aria-label="メインメニュー">{[['decks','単語帳',BookOpen],['import','CSV取り込み',Upload],['stats','学習の記録',BarChart3]].map(([key,label,Icon])=>{const I=Icon as typeof BookOpen;return <button key={key as string} disabled={busy} className={(tab===key||(key==='decks'&&['manage','study'].includes(tab)))?'active':''} onClick={()=>navigate(key as string)}><I size={17} aria-hidden style={{display:'inline',verticalAlign:'-3px',marginRight:6}}/>{label as string}</button>})}</nav><span className="subtle">{offline?'オフライン':'PC・スマホで同期'}</span></header>
 {offline&&<p className="error" role="status">インターネットに接続してください。学習結果はオンライン時に保存できます。</p>}{error&&<div className="error" role="alert">{error} <button className="text-button" disabled={busy} onClick={()=>run(async()=>{await refresh()})}>接続を再確認</button></div>}{notice&&<p className="notice" role="status">{notice}</p>}
 {loading?<section className="panel empty" style={{marginTop:32}} role="status">単語帳を読み込んでいます…</section>:auth?<section className="panel empty" style={{marginTop:32}}><h1>あなたの単語帳を、どこでも。</h1><p>PCとスマホで同じChatGPTアカウントにログインすると、単語帳と学習履歴を共有できます。</p><a className="primary" href="/signin-with-chatgpt?return_to=%2F" target="_top">ログインして始める</a></section>:<>
 {tab==='decks'&&<><div className="heading"><div><p className="eyebrow">YOUR STUDY SPACE</p><h1>今日も、ひとつずつ。</h1></div><button className="primary" onClick={()=>navigate('import')}><Plus size={18}/>単語帳を作る</button></div><div className="stats"><div className="stat"><span className="subtle">復習待ち</span><strong>{due}<small> 枚</small></strong></div><div className="stat"><span className="subtle">今日の学習</span><strong>{todayCount}<small> 回</small></strong></div><div className="stat"><span className="subtle">継続日数</span><strong>{streak}<small> 日</small></strong></div></div><div className="section-title"><h2>あなたの単語帳 <span className="badge">{data?.decks.length||0}</span></h2><button className="text-button" disabled={busy} onClick={()=>run(async()=>{await refresh();setNotice('最新の状態に更新しました。')})}><RefreshCw size={16} style={{display:'inline',verticalAlign:'-3px'}}/> 更新</button></div>{!data?.decks.length?<section className="panel empty"><BookOpen size={38} color="#245ce5" style={{margin:'0 auto 18px'}}/><h2>最初の単語帳を用意しましょう</h2><p>PCで作ったCSVを取り込むと、スマホからいつでも復習できます。「問題」と「答え」の2列から始められます。</p><div className="row" style={{justifyContent:'center'}}><button className="primary" onClick={()=>navigate('import')}><Upload size={18}/>CSVを取り込む</button><button className="secondary" disabled={busy} onClick={()=>run(async()=>{await api('',{action:'import',operationId:crypto.randomUUID(),name:'はじめての英単語（サンプル）',cards:[{front:'remember',back:'覚えている、思い出す',note:'Remember to take a break.'},{front:'curiosity',back:'好奇心',note:'Curiosity opens new doors.'},{front:'consistent',back:'一貫した、継続的な',note:'Small, consistent steps.'}]});await refresh();setNotice('3枚のサンプルを追加しました。「復習する」から試せます。')})}>サンプルで試す</button></div></section>:<div className="grid">{data.decks.map(d=><article className="deck" key={d.id}><div className="row spaced"><BookOpen size={24} color="#245ce5"/><span className="badge">{d.total} 枚</span></div><h3>{d.name}</h3><div><div className="row spaced subtle"><span>定着の目安</span><span>{d.learned} / {d.total} 枚</span></div><div className="line" style={{marginTop:8}}><span style={{width:`${d.total?100*d.learned/d.total:0}%`}}/></div></div><div className="row spaced"><span className="subtle">{d.due?`${d.due}枚が復習待ち`:'復習はひと休み'}</span><div className="row"><button className="text-button" disabled={busy} onClick={()=>openDeck(d)}>編集</button><button className={d.due?'primary':'secondary'} disabled={busy||offline||!d.due} onClick={()=>study(d)}>復習する</button></div></div></article>)}</div>}<p className="footer"><Smartphone size={16} style={{display:'inline',verticalAlign:'-3px'}}/> AndroidのChromeで開き、メニューから「ホーム画面に追加」。オンラインでご利用ください。</p></>}
 {tab==='import'&&<><div className="heading"><div><p className="eyebrow">IMPORT YOUR CARDS</p><h1>CSVから、すぐ単語帳に。</h1></div></div><ImportForm decks={data?.decks||[]} busy={busy} run={run} onDone={async(count)=>{await refresh();setTab('decks');setNotice(`${count}枚のカードを取り込みました。スマホにも同じ単語帳が表示されます。`)}}/></>}
 {tab==='manage'&&currentDeck&&<><div className="heading"><div><button className="text-button" onClick={()=>navigate('decks')}><ArrowLeft size={16} style={{display:'inline'}}/> 単語帳へ</button><h1 className="break">{currentDeck.name}</h1><p className="subtle">{cards.length}枚 · 復習予定は編集後も引き継がれます</p></div><button className="secondary" onClick={()=>{setName(currentDeck.name);setModal('rename')}}><MoreHorizontal size={20}/>管理</button></div><div className="row" style={{marginBottom:20}}><input aria-label="カードを検索" placeholder="問題・答え・タグで検索" value={search} onChange={e=>setSearch(e.target.value)} style={{flex:'1 1 240px'}}/><button className="primary" onClick={()=>{setEditing(null);setDraft(blank);manualOperation.current=crypto.randomUUID();setModal('card')}}><Plus size={18}/>カード追加</button><button className="secondary" onClick={()=>download(currentDeck.name+'.csv','\uFEFF'+[['問題','答え','補足','タグ'],...cards.map(c=>[c.front,c.back,c.note,c.tags])].map(row=>row.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8')}><Download size={17}/>CSV保存</button></div><div className="panel table-scroll"><table><thead><tr><th>問題 / 答え</th><th>次の復習</th><th>操作</th></tr></thead><tbody>{cards.filter(c=>[c.front,c.back,c.tags].join(' ').toLowerCase().includes(search.toLowerCase())).map(c=><tr key={c.id}><td><strong>{c.front}</strong><p>{c.back}</p>{c.tags&&<span className="badge">{c.tags}</span>}</td><td>{c.reviews?date(c.due):'未学習'}<p className="subtle">{c.reviews}回学習</p></td><td><button className="text-button" onClick={()=>{setEditing(c);setDraft(c);setModal('card')}}>編集</button></td></tr>)}</tbody></table>{cards.length===0&&<p className="empty">カードを追加してください。</p>}</div></>}
 {tab==='study'&&selected&&<div className="study"><div className="row spaced"><button className="text-button" disabled={busy} onClick={()=>{navigate('decks');void refresh().catch(()=>{})}}><ArrowLeft size={17} style={{display:'inline'}}/> 終了する</button><span className="subtle break">{selected.name}</span></div>{complete?<section className="panel empty" style={{marginTop:24}}><Check size={44} color="#17845b" style={{margin:'0 auto 20px'}}/><h1>今回の復習、おつかれさま。</h1><p>{session.length}枚を学習し、{right}枚を「わかった」と記録しました。難しいカードは10分後、わかったカードは1日以上あとに復習します。</p><button className="primary" onClick={()=>navigate('decks')}>単語帳に戻る</button></section>:card&&<><div className="row spaced" style={{marginTop:18}}><span className="subtle">{position+1} / {session.length} 枚</span><span className="badge">{card.reviews?'復習':'はじめて'}</span></div><div className="progress"><span style={{width:`${position/session.length*100}%`}}/></div><div className="flashcard" onTouchStart={e=>{touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;touch.current=null;if(revealed&&Math.abs(dx)>90&&Math.abs(dy)<60)rate(dx>0?'good':'again')}}><span className="eyebrow">{revealed?'QUESTION & ANSWER':'QUESTION'}</span><div className="question">{card.front}</div>{revealed?<><div className="answer">{card.back}</div>{card.note&&<p className="hint">{card.note}</p>}</>:<><button className="primary" onClick={()=>setRevealed(true)}>答えを見る</button><button className="text-button" onClick={()=>setHint(true)}>最初の1文字をヒントに</button>{hint&&<p className="hint">{Array.from(card.back)[0]}…</p>}</>}</div>{revealed?<div className="rating"><button className="danger" disabled={busy||offline||!!pending&&pending.rating!=='again'} onClick={()=>rate('again')}><span><RotateCcw size={17} style={{display:'inline',verticalAlign:'-3px'}}/> 難しい</span><small>{pending?.rating==='again'?'再試行も同じ記録として保存':'10分後にもう一度'}</small></button><button className="good" disabled={busy||offline||!!pending&&pending.rating!=='good'} onClick={()=>rate('good')}><span><Check size={18} style={{display:'inline',verticalAlign:'-3px'}}/> わかった</span><small>{Math.round(schedule(card,'good',Date.now()).interval)}日後に復習</small></button></div>:null}<p className="subtle" style={{textAlign:'center',marginTop:18}}>{busy?'保存しています…':revealed?'左へスワイプ：難しい ／ 右へ：わかった':'PCではスペースで答え、1・2キーで判定'}</p>{session.length===100&&<p className="subtle">1回の学習は100枚まで。残りは単語帳から続けられます。</p>}</>}</div>}
 {tab==='stats'&&<><div className="heading"><div><p className="eyebrow">SMALL STEPS, REAL PROGRESS</p><h1>学習の積み重ね。</h1></div><button className="secondary" disabled={busy} onClick={()=>run(async()=>{download('newanki-progress-'+today+'.json',JSON.stringify(await api('?export=1'),null,2));setNotice('単語帳・カード・学習履歴をJSONで保存しました。')})}><Download size={17}/>履歴を保存</button></div><div className="stats"><div className="stat"><span className="subtle">これまでの学習</span><strong>{data?.summary.count||0}<small> 回</small></strong></div><div className="stat"><span className="subtle">わかったの割合</span><strong>{data?.summary.count?Math.round(data.summary.good/data.summary.count*100):0}<small> %</small></strong></div><div className="stat"><span className="subtle">単語帳のカード</span><strong>{total}<small> 枚</small></strong></div></div><section className="panel"><div className="section-title"><h2>最近14日間</h2><span className="subtle">学習回数 · 日本時間</span></div><div className="chart" role="img" aria-label="過去14日間の日別学習回数">{Array.from({length:14},(_,i)=>{const day=jstDate(Date.now()-(13-i)*86400000),count=data?.daily.find(d=>d.day===day)?.count||0,max=Math.max(1,...(data?.daily.slice(0,14).map(d=>d.count)||[]));return <div className="day" key={day} title={`${day}: ${count}回`}><span>{count}</span><div className="bar" style={{height:`${Math.min(100,count/max*100)+2}px`}}/><span>{day.slice(8)}</span></div>})}</div></section><section className="panel" style={{marginTop:20}}><h2>最近の学習</h2><div className="table-scroll"><table><thead><tr><th>カード</th><th>判定</th><th>学習した日時</th></tr></thead><tbody>{data?.recent.map(r=><tr key={r.id}><td>{r.front}<p className="subtle">{r.name}</p></td><td>{r.rating==='good'?'わかった':'難しい'}</td><td>{date(r.reviewed_at)}</td></tr>)}</tbody></table>{!data?.recent.length&&<p className="empty subtle">カードを復習すると、ここに記録されます。</p>}</div></section><section className="notice"><strong>将来のAIによる進捗確認に向けて</strong><p className="subtle">学習日時・判定・回答時間・次回の復習予定を保存しています。履歴をJSONで取り出せます。自動監視や外部AIへの送信は、まだ有効になっていません。</p></section><p className="footer">復習間隔は「難しい」で10分、「わかった」で1日・3日・以後約2.2倍（最大365日）。間隔21日以上を定着の目安としています。アカウント：{data?.user.email}</p></>}
 </>}
 {modal==='card'&&<Modal title={editing?'カードを編集':'カードを追加'} onClose={()=>{if(!busy)setModal(null)}}><form className="form" onSubmit={saveCard}>{(['front','back','note','tags'] as const).map((key,i)=><label key={key}>{['問題','答え','補足（任意）','タグ（任意）'][i]}<textarea required={i<2} maxLength={[5000,10000,10000,500][i]} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}{error&&<p className="error" role="alert">{error}</p>}<div className="row spaced"><button className="primary" disabled={busy||offline} type="submit">{busy?'保存中…':'保存する'}</button>{editing&&<button className="danger" type="button" disabled={busy} onClick={()=>{if(window.confirm('このカードと学習履歴を削除しますか？'))void run(async()=>{await api('',{action:'deleteCard',deckId:selected?.id,cardId:editing.id});setCards((await api('?deck='+selected?.id)).cards);setModal(null);await refresh()})}}>カードを削除</button>}</div></form></Modal>}
 {modal==='rename'&&<Modal title="単語帳の管理" onClose={()=>{if(!busy)setModal(null)}}><form className="form" onSubmit={e=>{e.preventDefault();void run(async()=>{await api('',{action:'rename',deckId:selected?.id,name});await refresh();setModal(null)})}}><label>単語帳の名前<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>名前を保存</button><button className="danger" type="button" onClick={()=>setModal('delete')}>単語帳を削除…</button></form></Modal>}
 {modal==='delete'&&<Modal title="単語帳を削除しますか？" onClose={()=>{if(!busy)setModal(null)}}><p>「{currentDeck?.name}」の全カードと学習履歴が削除されます。この操作は元に戻せません。</p>{error&&<p className="error">{error}</p>}<div className="row" style={{marginTop:20}}><button className="secondary" disabled={busy} onClick={()=>setModal(null)}>キャンセル</button><button className="danger" disabled={busy} onClick={()=>run(async()=>{await api('',{action:'deleteDeck',deckId:selected?.id});await refresh();setModal(null);setTab('decks');setSelected(null)})}>削除する</button></div></Modal>}
 </div>
}

function ImportForm({decks,busy,run,onDone}:{decks:Deck[];busy:boolean;run:(fn:()=>Promise<void>)=>Promise<void>;onDone:(count:number)=>Promise<void>}){
 const [rows,setRows]=useState<string[][]>([]),[filename,setFilename]=useState(''),[encoding,setEncoding]=useState('utf-8'),[header,setHeader]=useState(true),[map,setMap]=useState([0,1,-1,-1]),[name,setName]=useState(''),[deck,setDeck]=useState(''),[error,setError]=useState('');const bytes=useRef<ArrayBuffer|null>(null),operation=useRef(crypto.randomUUID());
 const parse=(buffer:ArrayBuffer,enc:string)=>{try{const text=new TextDecoder(enc,{fatal:true}).decode(buffer),r=parseCsv(text);if(r.length>1001)throw new Error('1回の取り込みは1,000枚までです。');if(r.some(row=>row.length>100))throw new Error('列数が多すぎます（最大100列）。');setRows(r);const names=r[0].map(x=>x.trim().toLowerCase());const aliases=[['問題','表','単語','front','question','term'],['答え','裏','意味','back','answer','definition'],['補足','説明','note','notes','explanation'],['タグ','tags','tag']];const guessed=aliases.map(a=>names.findIndex(n=>a.includes(n)));const hasHeader=guessed[0]>=0&&guessed[1]>=0;setHeader(hasHeader);setMap(hasHeader?guessed:[0,1,-1,-1]);setError('');operation.current=crypto.randomUUID()}catch(e){setRows([]);setError(e instanceof TypeError?'文字コードが一致しません。Shift_JISを選んでみてください。':(e as Error).message)}};
 const width=Math.max(0,...rows.map(r=>r.length)),content=header?rows.slice(1):rows;
 const mapped=content.map(row=>({front:row[map[0]]?.trim()||'',back:row[map[1]]?.trim()||'',note:row[map[2]]?.trim()||'',tags:row[map[3]]?.trim()||''}));
 const invalid=mapped.flatMap((r,i)=>!r.front||!r.back||r.front.length>5000||r.back.length>10000||r.note.length>10000||r.tags.length>500?[i+(header?2:1)]:[]);
 const duplicates=mapped.length-new Set(mapped.map(r=>JSON.stringify([r.front,r.back]))).size;
 return <section className="panel"><form className="form" onSubmit={e=>{e.preventDefault();if(invalid.length||!mapped.length||map[0]===map[1])return;void run(async()=>{const r=await api('',{action:'import',operationId:operation.current,deckId:deck||undefined,name,cards:mapped});await onDone(r.count)})}}>
 <div className="row spaced"><h2>1. CSVファイルを選ぶ</h2><button type="button" className="text-button" onClick={()=>download('newanki-template.csv','\uFEFF問題,答え,補足,タグ\r\nremember,覚えている・思い出す,Remember to take a break.,英語\r\ncuriosity,好奇心,Curiosity opens new doors.,英語\r\n','text/csv;charset=utf-8')}><Download size={16} style={{display:'inline'}}/> テンプレート</button></div><p className="subtle">UTF-8・Shift_JIS対応。1回に1,000枚、2MBまで。引用符で囲まれた改行やカンマも取り込めます。</p><div className="upload"><Upload size={30} color="#245ce5" style={{margin:'0 auto 10px'}}/><label>ファイルを選択<input type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setRows([]);setError('ファイルは2MB以下にしてください。');return}setFilename(file.name);if(!name)setName(file.name.replace(/\.csv$/i,''));bytes.current=await file.arrayBuffer();parse(bytes.current,encoding)}}/></label>{filename&&<span className="subtle break">{filename}</span>}</div><label>文字コード<select value={encoding} disabled={busy} onChange={e=>{setEncoding(e.target.value);if(bytes.current)parse(bytes.current,e.target.value)}}><option value="utf-8">UTF-8（推奨）</option><option value="shift_jis">Shift_JIS（ExcelのCSVなど）</option></select></label>{error&&<p className="error" role="alert">{error}</p>}
 {rows.length>0&&<><h2>2. 列と取り込み先を確認</h2><label style={{display:'flex',alignItems:'center'}}><input type="checkbox" style={{width:20,minHeight:20}} checked={header} disabled={busy} onChange={e=>{setHeader(e.target.checked);operation.current=crypto.randomUUID()}}/> 1行目は見出し</label><div className="grid">{['問題','答え','補足（任意）','タグ（任意）'].map((label,i)=><label key={label}>{label}<select value={map[i]} disabled={busy} onChange={e=>{setMap(map.map((v,j)=>i===j?Number(e.target.value):v));operation.current=crypto.randomUUID()}}>{i>1&&<option value={-1}>取り込まない</option>}{Array.from({length:width},(_,j)=><option key={j} value={j}>{j+1}列目{header?'：'+rows[0][j]:''}</option>)}</select></label>)}</div><label>取り込み先<select value={deck} disabled={busy} onChange={e=>{setDeck(e.target.value);operation.current=crypto.randomUUID()}}><option value="">新しい単語帳を作成</option>{decks.map(d=><option key={d.id} value={d.id}>{d.name}に追加</option>)}</select></label>{!deck&&<label>単語帳の名前<input required maxLength={100} value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label>}<div className="section-title"><h2>3. プレビュー</h2><span className="badge">{mapped.length}枚</span></div>{invalid.length>0&&<p className="error">問題・答えが空欄、または文字数が上限を超えています。CSVの{invalid.slice(0,10).join('、')}行目を修正してください。問題5,000文字、答え・補足10,000文字、タグ500文字までです。</p>}{map[0]===map[1]&&<p className="error">問題と答えには別々の列を選んでください。</p>}{duplicates>0&&<p className="notice">同じ問題・答えの組み合わせが{duplicates}枚あります。重複もそのまま取り込みます。</p>}<div className="table-scroll"><table><thead><tr><th>問題</th><th>答え</th><th>補足</th></tr></thead><tbody>{mapped.slice(0,5).map((r,i)=><tr key={i}><td>{r.front||'（空欄）'}</td><td>{r.back||'（空欄）'}</td><td>{r.note}</td></tr>)}</tbody></table></div><p className="subtle">先頭5枚を表示。既存の単語帳へ取り込む場合はカードを追加し、現在のカードや学習履歴は残します。</p><button className="primary" disabled={busy||!mapped.length||!!invalid.length||map[0]===map[1]} type="submit">{busy?'保存しています…':`${mapped.length}枚を取り込む`}</button></>}
 </form></section>
}


